name: meemmoto
favicon: null
layout_spectrum: 0.6045361286960542
typography_spectrum: 0.6092264680191875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4463982561137527
  lightness: 0.6852184948511422
  saturation: 0.480415913509205
  rhythmicContrast: 0.9396057154517621
purpose: []
