name: meemmoto
favicon: null
layout_spectrum: 0.49135
typography_spectrum: 0.78262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f8dc0c'
    - '#c9b209'
    - '#8a7b06'
    - '#3e3603'
  brandStrength: 0.4463982561137527
  lightness: 0.6852184948511422
  saturation: 0.480415913509205
  rhythmicContrast: 0.9396057154517621
purpose: []
